version: "2"
services:
  app:
    image: acepabdurohman/simple-web-repo:0.1
    ports:
      - "4000:7000"
    container_name: simple-web-1
    depends_on:
      - mysql56
  mysql56:
    image: mysql:5.6
    ports:
      - "3200:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin1234
      - MYSQL_DATABASE=db_training
    container_name: mysql56